---
include:
  - board: seeeduino_xiao_ble
    shield: portago9
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: seeeduino_xiao_ble
    shield: settings_reset

  - board: seeeduino_xiao_ble
    shield: portago9_dongle prospector_adapter
