---
include:
  - board: seeeduino_xiao_ble
    shield: portago9_body rgbled_adapter

  - board: seeeduino_xiao_ble
    shield: settings_reset

  - board: seeeduino_xiao_ble
    shield: portago9_dongle prospector_adapter
